version: '3'
services:

  mysql:
      networks:
        - default
      image: mysql:latest
      platform: linux/amd64
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: 'deres'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      volumes:
        - "./database/schemas:/docker-entrypoint-initdb.d"

  api:
    networks:
      - default
    build:
      context: .
    ports:
      - "8081:8080"

networks:
  default:
    driver: bridge